###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum

from pydantic import BaseModel, ConfigDict

from typing_extensions import TypeAlias, Literal
from typing import Dict, Generic, List, Optional, TypeVar, Union

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class AgentInput(BaseModel):
    query: Optional[str] = None

class AgentOutput(BaseModel):
    response: Optional[str] = None
    action: Optional[str] = None

class AgentPlannerInput(BaseModel):
    paragraph: Optional[str] = None
    available_tools: List[str]

class AgentPlannerOutput(BaseModel):
    plan_description: Optional[str] = None
    tool_calls: List["ToolCall"]

class AgentWithToolsInput(BaseModel):
    query: Optional[str] = None
    available_tools: List[str]

class AgentWithToolsOutput(BaseModel):
    response: Optional[str] = None
    tool_to_use: Optional[str] = None
    tool_parameters: Optional[str] = None

class Resume(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    experience: List[str]
    skills: List[str]

class ToolCall(BaseModel):
    tool_name: Optional[str] = None
    parameters: Optional[str] = None
    purpose: Optional[str] = None
